language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install: "pip install pytest"
script: "pytest"
notifications:
  on_success: change
  on_failure: always
  template:
      - "[%{build_number}] %{message} (%{build_url})"